package cencosud.remuneraciones;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vendedor implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   @org.kie.api.definition.type.Label(value = "montoVenta")
   private int montoVenta;
   @org.kie.api.definition.type.Label(value = "comision")
   private int comision;
   @org.kie.api.definition.type.Label(value = "sueldo")
   private int sueldo;

   public Vendedor()
   {
   }

   public int getMontoVenta()
   {
      return this.montoVenta;
   }

   public void setMontoVenta(int montoVenta)
   {
      this.montoVenta = montoVenta;
   }

   public int getComision()
   {
      return this.comision;
   }

   public void setComision(int comision)
   {
      this.comision = comision;
   }

   public int getSueldo()
   {
      return this.sueldo;
   }

   public void setSueldo(int sueldo)
   {
      this.sueldo = sueldo;
   }

   public Vendedor(int montoVenta, int comision, int sueldo)
   {
      this.montoVenta = montoVenta;
      this.comision = comision;
      this.sueldo = sueldo;
   }

}