package cencosud.remuneraciones;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Vendedor implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public Vendedor() {
    }

}