package cencosud.remuneraciones;


package cencosud.remuneraciones;

//from row number: 1
rule "Row 1 calculoRemuneraciones"
	ruleflow-group "calculoRemus"
	dialect "mvel"
	when
		f1 : Vendedor( montoVenta >= 500000 , montoVenta <= 600000 )
	then
		f1.setComision( 5 );
		f1.setSueldo(fi.setSueldo * 1.05);
end

//from row number: 2
rule "Row 2 calculoRemuneraciones"
	ruleflow-group "calculoRemus"
	dialect "mvel"
	when
		f1 : Vendedor( montoVenta >= 600001 , montoVenta <= 700000 )
	then
		f1.setComision( 10 );
		f1.setSueldo(fi.setSueldo * 1.1);
end

//from row number: 3
rule "Row 3 calculoRemuneraciones"
	ruleflow-group "calculoRemus"
	dialect "mvel"
	when
		f1 : Vendedor( montoVenta >= 700001 , montoVenta <= 800000 )
	then
		f1.setComision( 15 );
		f1.setSueldo(fi.setSueldo * 1.15);
end

//from row number: 4
rule "Row 4 calculoRemuneraciones"
	ruleflow-group "calculoRemus"
	dialect "mvel"
	when
		f1 : Vendedor( montoVenta >= 800001 , montoVenta <= 900000 )
	then
		f1.setComision( 20 );
		f1.setSueldo(fi.setSueldo * 1.2);
end

//from row number: 5
rule "Row 5 calculoRemuneraciones"
	ruleflow-group "calculoRemus"
	dialect "mvel"
	when
		f1 : Vendedor( montoVenta >= 900001 , montoVenta <= 10000000 )
	then
		f1.setComision( 25 );
		f1.setSueldo(fi.setSueldo * 1.25);
end
